server:
  port: 8081
spring:
  cloud:
    config:
      server: 
        git:
          default-label: circuit-breaker
          uri: https://github.com/martinema/microserviciosSpringBoot.git
          username: martinema
          password: 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
          search-paths: config-data
  application:
    name: config-servicios
  
